use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/keove/PodSpecs.git'

target 'KOTMSwift_Example' do
  pod 'KOTMSwift', :path => '../'
	pod 'Konnekt'
pod 'MaterialComponents/Buttons'
pod 'MaterialComponents/Buttons+ButtonThemer'
pod 'MaterialComponents/TextFields'
pod 'MaterialComponents/TextFields+ColorThemer'
pod 'MaterialComponents/TextFields+Theming'
pod 'MaterialComponents/Snackbar'
pod 'MaterialComponents/Snackbar+ColorThemer'
pod 'MaterialComponents/schemes/Color'

  target 'KOTMSwift_Tests' do
    inherit! :search_paths

    
  end
end
